### ISSUE TITLE
Is this a 32bit plugin?

### ISSUE THREAD

**Issue by Cris--** [morukutsu/LondonClockT#3]
I think so or?
Can't load it in [Kushview Element](https://kushview.net/products/element/) VST Host

**Comment by morukutsu** [comment]
Sorry for the long delay! I didn't check Github in a long time.
As far as I remember, this might be a 32bit build.
If you need a 64bits build, as far as I remember, it should not be too hard to rebuild.
I don't have access to a Windows PC at the moment though. But I can still investigate if you need it! Thanks

**Comment by mungewell** [comment]
I can confirm that it's a 32bit VST, and I was able to use with 32bit Cantabile.
A 64bit version would be nice if someone can build it..

**Comment by morukutsu** [comment]
Hello, sorry I forgot I had to work on this...

I updated the project to the latest juce version and built a 64bit VST3 version of it here: https://github.com/morukutsu/LondonClockT/blob/master/bin/LondonClockT.vst3

Could you check if it's working for you?
I quickly tested, I can load it and it works with the latest Bitwig Studio version, but I didn't test it in Catabile.

Thanks!

**Comment by Cris--** [comment]
Works on Windows with Kushview Element as host!

**Comment by mungewell** [comment]
I can also confirm that it works under Windows 10 with Cantabile 64bit (had to re-install a newer version for VST3 support).

Thanks you!

**Comment by morukutsu** [comment]
Perfect, thanks for testing!
